#ifndef GAMECONFIG_H
#define GAMECONFIG_H

// Protocol size
#define BUFFERSIZE 2048
// maximum client in server
#define MAXSIMULTANEOUSCLIENTS 100

#define GAME_CLIENT_WAITING_SERVER 0

#define GAME_STATUS_ERROR 2
#define GAME_STATUS_DISCONNECT 3
#define GAME_STATUS_WAITING_PLAYER 4
#define GAME_STATUS_FIRST_CONNECTION 5
#define GAME_STATUS_WAITING_GAME 7
#define GAME_STATUS_READY_TO_PLAY 8
#define GAME_STATUS_JOIN 10

//choice 
#define GAME_CHOICE_COLLABORATE 30
#define GAME_CHOICE_BETRAY 31

//result 
#define GAME_CHOICE_BOTH_COLLAB 32
#define GAME_CHOICE_BOTH_BETRAY 33
#define GAME_CHOICE_PLAYER1_WIN 34
#define GAME_CHOICE_PLAYER2_WIN 35
#define GAME_CHOICE_EQUALITY 36

#define GAME_STATUS_START 12
#define GAME_STATUS_RESULT 15
#define GAME_STATUS_WAITING_RESULT 16
#define GAME_STATUS_WAITING_RESULT_PLAYER 17
#define GAME_STATUS_END 20
#define MAX_GAME 50

// status player
#define GAME_PLAYER_1 101
#define GAME_PLAYER_2 102

#define GAME_STATUS_MESSAGE 111
#define GAME_ACTION_MESSAGE 112

#endif